### PR TITLE
Fixed errors @ lines 193 and 257.

### PR DESCRIPTION
**Pull request by matweldon**
@ 193 '1:1:n' replaced with '1:n'
@ 257 'duration' in regex replaced with '^duration$'

### CODE REVIEW

**Comment by matweldon** [comment]
Not sure what failed here?

**Comment by Demetrio92** [comment]
Can anyone explain me what is the purpose of grepping the name? In my opinion this is a flawed approach. I tested your fix and it completely disregards the `duration_in_traffic` column even if I provide the parameter `traffic_model`. 
My suggestion is to use one of them depending on the parameter `traffic_model`. And allow a value `'None'`, where the parameter is simply not submitted to gmaps API, which should also be default. 

I will submit a PR for that later today.

**Comment by matweldon** [comment]
Yes, now you mention it it's weird. `grep("^duration$",string,value=T)` always evaluates as "duration" or `character(0)`. The original was causing errors though.

I also noticed that there are some other bugs. For example, the function appears to completely ignore `arr_date` and `arr_time` even if they are provided.

It would probably be best to implement the `match.arg` pattern for function arguments, which could then replace all the text checking. eg. `traffic_model = c("best_guess","optimistic","pessimistic")` in the arguments list, with `traffic_model = match.arg(traffic_model)` in the body of the function.

I didn't implement this yet because I spotted other bugs, and then I moved on to another project.

**Comment by Demetrio92** [comment]
@matweldon I submitted a PR and contacted the maintainer of the package. 
I think, it's better to fix this one, than write it from scratch. If I will have to rely on the package a lot in the future, I will try to fix the other things and help with PRs. 
For now, let's hope my rather quick fix will be merged and pushed to CRAN at all.

**Comment by Demetrio92** [comment]
fixed somewhere else #35

**Pull request closed without merging**
